import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://65d8117b8e8d878bc749fba9--vermillion-boba-db22e0.netlify.app/">mohd imran mohd husain kacchi</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/desktopone">Login From</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
